/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdjustmentLog {
  'id' : bigint,
  'itemId' : bigint,
  'adjustedByEmail' : string,
  'notes' : string,
  'timestamp' : bigint,
  'itemName' : string,
  'newQuantity' : bigint,
  'amount' : bigint,
  'adjustmentType' : { 'add' : null } |
    { 'remove' : null },
  'adjustedBy' : Principal,
}
export type AppRole = { 'admin' : null } |
  { 'staff' : null } |
  { 'guest' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface InventoryItem {
  'id' : bigint,
  'sku' : string,
  'lowStockThreshold' : bigint,
  'supplier' : string,
  'name' : string,
  'createdAt' : bigint,
  'unit' : string,
  'description' : string,
  'updatedAt' : bigint,
  'expirationDate' : [] | [bigint],
  'barcode' : string,
  'quantity' : bigint,
  'category' : string,
  'price' : number,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'status' : UserStatus,
  'principal' : Principal,
  'lastLoginAt' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'role' : AppRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInventoryItem' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      string,
      number,
      string,
      [] | [bigint],
      string,
    ],
    bigint
  >,
  'adjustInventory' : ActorMethod<
    [bigint, { 'add' : null } | { 'remove' : null }, bigint, string],
    undefined
  >,
  'approveUser' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAdjustmentLogs' : ActorMethod<[], Array<AdjustmentLog>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getInventoryItemsByCategory' : ActorMethod<[string], Array<InventoryItem>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'registerOrLogin' : ActorMethod<[], UserProfile>,
  'rejectUser' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'seedDemoInventory' : ActorMethod<[], undefined>,
  'seedDemoUsers' : ActorMethod<[], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateInventoryItem' : ActorMethod<[bigint, InventoryItem], undefined>,
  'updateUserRole' : ActorMethod<[Principal, AppRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];