/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BulkInventoryRecord = IDL.Record({
  'partNumber' : IDL.Nat,
  'partName' : IDL.Text,
  'description' : IDL.Text,
  'stockThreshold' : IDL.Nat,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const BulkImportError = IDL.Record({
  'rowIndex' : IDL.Nat,
  'reason' : IDL.Text,
  'record' : BulkInventoryRecord,
});
export const BulkImportResult = IDL.Record({
  'skippedRows' : IDL.Vec(BulkImportError),
  'newRecords' : IDL.Vec(BulkInventoryRecord),
  'newRecordCount' : IDL.Nat,
  'updatedCount' : IDL.Nat,
  'createdCount' : IDL.Nat,
  'skippedCount' : IDL.Nat,
});
export const AdjustmentLog = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Nat,
  'adjustedByEmail' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'itemName' : IDL.Text,
  'newQuantity' : IDL.Nat,
  'amount' : IDL.Nat,
  'adjustmentType' : IDL.Variant({ 'add' : IDL.Null, 'remove' : IDL.Null }),
  'adjustedBy' : IDL.Principal,
});
export const UserStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AppRole = IDL.Variant({
  'admin' : IDL.Null,
  'staff' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'status' : UserStatus,
  'principal' : IDL.Principal,
  'lastLoginAt' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : AppRole,
  'email' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'lowStockThreshold' : IDL.Nat,
  'supplier' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'expirationDate' : IDL.Opt(IDL.Int),
  'barcode' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInventoryItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Int),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'adjustInventory' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({ 'add' : IDL.Null, 'remove' : IDL.Null }),
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'approveUser' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkImportInventory' : IDL.Func(
      [IDL.Vec(BulkInventoryRecord)],
      [BulkImportResult],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAdjustmentLogs' : IDL.Func([], [IDL.Vec(AdjustmentLog)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getInventoryItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InventoryItem)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'registerOrLogin' : IDL.Func([], [UserProfile], []),
  'rejectUser' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'seedDemoInventory' : IDL.Func([], [], []),
  'seedDemoUsers' : IDL.Func([], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateInventoryItem' : IDL.Func([IDL.Nat, InventoryItem], [], []),
  'updateUserRole' : IDL.Func([IDL.Principal, AppRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BulkInventoryRecord = IDL.Record({
    'partNumber' : IDL.Nat,
    'partName' : IDL.Text,
    'description' : IDL.Text,
    'stockThreshold' : IDL.Nat,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const BulkImportError = IDL.Record({
    'rowIndex' : IDL.Nat,
    'reason' : IDL.Text,
    'record' : BulkInventoryRecord,
  });
  const BulkImportResult = IDL.Record({
    'skippedRows' : IDL.Vec(BulkImportError),
    'newRecords' : IDL.Vec(BulkInventoryRecord),
    'newRecordCount' : IDL.Nat,
    'updatedCount' : IDL.Nat,
    'createdCount' : IDL.Nat,
    'skippedCount' : IDL.Nat,
  });
  const AdjustmentLog = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : IDL.Nat,
    'adjustedByEmail' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'itemName' : IDL.Text,
    'newQuantity' : IDL.Nat,
    'amount' : IDL.Nat,
    'adjustmentType' : IDL.Variant({ 'add' : IDL.Null, 'remove' : IDL.Null }),
    'adjustedBy' : IDL.Principal,
  });
  const UserStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AppRole = IDL.Variant({
    'admin' : IDL.Null,
    'staff' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'status' : UserStatus,
    'principal' : IDL.Principal,
    'lastLoginAt' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : AppRole,
    'email' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'lowStockThreshold' : IDL.Nat,
    'supplier' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'expirationDate' : IDL.Opt(IDL.Int),
    'barcode' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInventoryItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Int),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'adjustInventory' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({ 'add' : IDL.Null, 'remove' : IDL.Null }),
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'approveUser' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkImportInventory' : IDL.Func(
        [IDL.Vec(BulkInventoryRecord)],
        [BulkImportResult],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAdjustmentLogs' : IDL.Func([], [IDL.Vec(AdjustmentLog)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getInventoryItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'registerOrLogin' : IDL.Func([], [UserProfile], []),
    'rejectUser' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'seedDemoInventory' : IDL.Func([], [], []),
    'seedDemoUsers' : IDL.Func([], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateInventoryItem' : IDL.Func([IDL.Nat, InventoryItem], [], []),
    'updateUserRole' : IDL.Func([IDL.Principal, AppRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };